In [22]:
import numpy as np

In [31]:
test = [
    [[1,2,3], [4,5,6], [7,8,9]],
    [[9,8,7], [6,5,4], [3,2,1]],
]

test_b = [
    [[1,2,3], [4,5,6], [7,8,9]],
    [[9,8,7], [6,5,4], [3,2,1]],
]

In [32]:
test

[[[1, 2, 3], [4, 5, 6], [7, 8, 9]], [[9, 8, 7], [6, 5, 4], [3, 2, 1]]]

In [51]:
test_np = np.array(test)
test_nb = test_np.copy()

print(test_np)
print(test_nb)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[9 8 7]
  [6 5 4]
  [3 2 1]]]
[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[9 8 7]
  [6 5 4]
  [3 2 1]]]


In [60]:
test_np.shape


(2, 3, 3)

In [63]:
test_np[1,:,:]

array([[9, 8, 7],
       [6, 5, 4],
       [3, 2, 1]])

In [41]:
test_np = np.append(test_np, "test")

In [42]:

print(test_np)
print(test_nb)

['1' '2' '3' '4' '5' '6' '7' '8' '9' '9' '8' '7' '6' '5' '4' '3' '2' '1'
 'test']
[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[9 8 7]
  [6 5 4]
  [3 2 1]]]


In [34]:
if (test_np == test_nb):
    print("1")
else:
    print("2")

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [50]:
test_np.tolist() == test_nb.tolist()

False

In [56]:
(test_np.reshape(18))

array([1, 2, 3, 4, 5, 6, 7, 8, 9, 9, 8, 7, 6, 5, 4, 3, 2, 1])

In [57]:
len(test_np)

2